### ISSUE TITLE
DUO and i3

### ISSUE THREAD

**Issue by makramsg** [jbasen/Crestron-Shelly#1]
Hi, thank you for the amazing work!
I am moving into a new house and I am installing a combination of i3, DUO spots, and shelly 2.5.

I tested the 2.5 functionality and it is amazing!

do you plan on adding i3 and duo support in the future?

thank you

**Comment by jbasen** [comment]
Hi
I originally looked at supporting the duo bulb but ran into an issue.  Because the bulb has limited memory it doesn't include functionality to report its status back to a control system.  So, if, for example, the Shelly app is used by someone to control the bulb then the Crestron system has no idea if the bulb is on, or off.  So, rather than develop something that would be problematic for users I simply left that out.

However, I think adding support for the Shelly I3 would be a good idea.  I'll look into doing that.

Thanks

**Comment by jbasen** [comment]
I now have an i3 on order.  Provided the mail gets it here in a reasonable amount of time I expect I can add i3 support within 2 weeks.

**Comment by makramsg** [comment]
Thats great. Thank you so much for the great work. If there is anything i can assist with please let me know. I will be installing over 60 duos, 20 2.5s, 10 i3s. So i can help with testing if you want

**Comment by jbasen** [comment]
Thanks.  I'll let you know.

**Comment by jbasen** [comment]
I just wanted to let you know that I've uploaded v4 of the code.  This version now has a module dedicated to the Shelly i3.
Thanks
