### ISSUE TITLE
Shelly 2.5

### ISSUE THREAD

**Issue by meltsys** [jbasen/Crestron-Shelly#10]
Hi, again congrats for your work and for sharind it with the community.

I tested a Shelly 2.5 in relay mode with your modules Shelly Relay V1 and V3.
I don't get feedback of the relay when it's switch from the Shelly app.

I tried with a TCP server to be sure the I/O URL Actions are sent correctly from the Shelly 2.5.
And I get the URL on Crestron TCP server.
I saw Shelly 2.5 doesn't close the connection after sending the GET request. I must disable and  re-enable the server to receive another I/O URL Actions.

Do you have any idea ?
May be it is again a S# DB version :/ I'm testing with a MC3 !

Thank you for your support

**Comment by jbasen** [comment]
The most probably reasons this could occur are:

1) The I/O url action isn't formatted properly.  The programming is very picky about this so if it isn't formatted properly it won't get parsed properly and feedback won't work.  For example, for the output switched on url it needs to be in the format of (where the ip address of the crestron processor is 192.168.0.10, the port you have specified on the Shelly comm manager module is 9000d, and this is relay 1 of 2 on the Shelly 2.5 )

http://192.168.0.10:9000/relay/0/state/on/

Note relay 1 is channel 0 and relay 2 is channel 1.

2) In the Shelly relay module you must specify the ip address of the Shelly 2.5 on your network.  So, you have to either give the Shelly 2.5 a static IP address or a DHCP reservation.  If the IP address of the Shelly 2.5 changes then the feedback messages won't be picked up by the Shelly relay module

3) The port for communications specified in the I/O url actions must match the communications port specified in the parameter field of the Shelly comm manager module.  By default I set this to 9000d

Hope this helps

**Comment by meltsys** [comment]
Hello,

Thank you for your reply.
I double checked this but everything was correct :(
do you think the S# library work only with latest Cretsron FW and not with MC3 ?

Thank you

**Comment by jbasen** [comment]
There shouldn't be a problem with the MC3 as the code doesn't use https.  This is one of the reasons I've kept the code using http as that allows people with an MC3 to use it.  So, one other thing to check.  Make sure your i/o url action is http and not https

One last thing.  Are you using a username and password?  That is one area that has not been well tested.

I'll try and get a test system setup again to double check the code though it will probably take a number of weeks as I have a bunch of projects to complete right now.

**Comment by meltsys** [comment]
i/o url action is http with no username/password

One thing : I'm running the latest Shelly device firwmare.
No worries to solve it soon, that was just an information I would share with you :)

Thanks again for all your swift replies

**Comment by jbasen** [comment]
Hi

I had a few minutes so I pulled out a PM2.5, wired it up, and created a test program for my MC3 to see what is happening.  I just did a very basic test with the on/off url actions on relay channel 0.  For me, everything worked fine.  I have a pushbutton switch connected to the switch 1 input on the PM2.5 so I could change the state of the relay and force the update through the URL Action.  A few things to look at

1) My MC3 is at IP address 192.168.1.3 and in the comm manager I've specified port 9000 for communications.

2) I have the PM2.5 set to relay mode in the device settings

3) My I/O URL Actions are as follows:

http://192.168.1.3:9000/relay/0/state/on/
http://192.168.1.3:9000/relay/0/state/off/

Make sure you include the trailing "/" character as specified in the help.  Otherwise it won't work.

4) On the PM2.5 make sure you have the URL action enable checkbox checked and make sure that after you enter the url action you click the save button.  I am doing all this on the PM2.5 web page, not using the Shelly app.  I simply find it easier.  

Hope this helps
