### ISSUE TITLE
Position Shelly 2.5 in shutter mode.

### ISSUE THREAD

**Issue by micdre** [jbasen/Crestron-Shelly#32]
Hi,

Is it possible to create an analog input to give a  position in the 2.5 V21 module?

Kind regards, Michel

**Comment by jbasen** [comment]
Hi,

I'm a little confused.  The Shelly Roller v2.1 module that is specifically for the situation when the Shelly 2.5 is used in roller mode already has an analog output for position.  The Shelly Relay v6 module doesn't have a position output because that is only for use when the Shelly 2.5 is used in relay mode.

Thanks

**Comment by micdre** [comment]
I ment roller mode....

Met vriendelijke groet,
With kind regards,
Michel Drenthen

BlueMail voor Android<https://bluemail.me> downloaden
Op 17 feb. 2023, om 20:40, jbasen ***@***.******@***.***>> schreef:

Hi,

I'm a little confused. The Shelly Roller v2.1 module that is specifically for the situation when the Shelly 2.5 is used in roller mode already has an analog output for position. The Shelly Relay v6 module doesn't have a position output because that is only for use when the Shelly 2.5 is used in relay mode.

Thanks

**Comment by micdre** [comment]
Hi,

What i ment is that the shutter module gets an analog input.
So you can set the shutter position by an analog value.

Met vriendelijke groet,
With kind regards,
Michel Drenthen

BlueMail voor Android<https://bluemail.me> downloaden
Op 17 feb. 2023, om 20:40, jbasen ***@***.******@***.***>> schreef:

Hi,

I'm a little confused. The Shelly Roller v2.1 module that is specifically for the situation when the Shelly 2.5 is used in roller mode already has an analog output for position. The Shelly Relay v6 module doesn't have a position output because that is only for use when the Shelly 2.5 is used in relay mode.

Thanks

**Comment by jbasen** [comment]
Sorry @micdre.  My mistake.  Yes, I will look at adding an analog input for position in the next release.

Thanks

**Comment by jbasen** [comment]
Here is something to test.  There are 2 changes in this version

1) The addition of a position input on the roller shutter module.  Note - there is a new version of this module in the demo program.  You must replace the version in program with this version.

2) There is an architectural change in the program to overcome a memory leak in the underlying class library.  Hopefully you won't notice anything different because of this work.  The change is within the Shelly.clz file

NOTE - I have not been able to test this code; especially the roller shutter code change.  For the roller shutter code to operate you must go through the Shelly 2.5 calibration process.  While I have a Shelly 2.5 to test with I don't have a shade motor to connect to it with a shade that I could run through the calibration process.

Here is a link to download the test version

https://1drv.ms/u/s!AjlldUMTB6AFgoIS7t7yhozykqCZ-w?e=frlmNl

Let me know how it goes.

Thanks

**Comment by jbasen** [comment]
Thanks @micdre 
I'm glad everything is working.  The modules do provide for real time feedback through the "URL to Post Events to" that gets defined on the Maker API configuration page.  However, devices like this typically don't provide the kind of real time feedback you're looking for.  I'm working on an addition requested by another user.  I'll post this change when I've completed the other work. 
Thanks again.

**Comment by jbasen** [comment]
The code for this has been included in v23 that is now available on GitHub
