### ISSUE TITLE
Shelly BLU HT Integration

### ISSUE THREAD

**Issue by DavidPrendergast** [jbasen/Crestron-Shelly#40]
Hi Jay, I'm a long time user and really appreciate the work you're doing with Shelly and Crestron! I've purchased a few of the BLU HT devices and wondering if you have any plans to include these into the next release? They're incredibly useful and am looking at the possibility of rolling them out in all rooms in my home.

**Comment by jbasen** [comment]
Hi David, 

Adding support for BLU devices is challenging for me because I'm not a JavaScript programmer.   BLU devices require JavaScript code to be loaded onto the Shelly devices that the BLU device is connected to.  I had been receiving help with this from someone that works at Shelly.  Unfortunately, that person is no long with the company.  

Do you happen to know JavaScript?  If so I could work with you to modify one of the scripts I already have to work with the BLU H&T and I could make the other driver changes necessary for that to all work.  

Let me know.  

Thanks.  

Jay

**Comment by DavidPrendergast** [comment]
Hi Jay, apologies on the delay in responding. Unfortunately I'm not a Javscript programmer either and it's been a long time since I've even looked at it!

I wonder if you put the request out to the Crestron Programmers Facebook or groups.io page would any of the guys with Javascript be interested!? I do hope you get there in the end though and will keep an eye out for future updates.

Appreciate the response and work you put in to this.

Dave.

**Comment by jbasen** [comment]
Hi Dave,

I can do that but I have to choose the timing carefully.  If I'm asking a random person for help I have to make sure that my schedule is clear enough so I'm not in the position of finding myself too busy and holding them up.  Right now I'm tied up with some articles and product evaluations so it will take some time.  

Thanks

Jay

**Comment by jbasen** [comment]
I have figured out a way to do this without requiring custom JavaScript.  I should have an driver set update in the not too distant future.  Thanks

**Comment by jbasen** [comment]
Version 32 with support for the BLU H&T along with the BLU 4 button keypad has been posted to GitHub.
