### ISSUE TITLE
Shelly BLU TRV

### ISSUE THREAD

**Issue by SlawekWWW** [jbasen/Crestron-Shelly#44]
Hi,

Does the program support Shelly BLU TRV devices?
https://www.shelly.com/products/shelly-blu-trv-3-pack

Thanks

**Comment by jbasen** [comment]
At this point it doesn't and I am skeptical that I could make it work due to the requirement of the BLU USB gateway for integration. 

As a work around you could integrate the TRV through Home Assistant and then use the technique I outline in this article to integrate HA and Crestron: https://restechtoday.com/my-experience-integrating-crestron-and-home-assistant/
