### ISSUE TITLE
Getting Shelly Plus Plug US To Work

### ISSUE THREAD

**Issue by waffles0042** [jbasen/Crestron-Shelly#48]
Hello jbasen;

I came across your module and have been trying to get it to work with my Shelly Plus Plug US (https://a.co/d/4roEZda). So far, no luck, so I just wanted to confirm that your module does in fact support this particular device.

If so, have I interpreted the F1 instructions to set up a plug correctly?
- 192.168.20.176 is the address of the plug.
- I tried the Count setting with Zero and One, but no luck.
![2024-12-27_10h24_13](https://github.com/user-attachments/assets/6ebe585e-4ffc-4289-9f72-e8b6de3255c6)

![2024-12-27_10h45_03](https://github.com/user-attachments/assets/b73f5607-44f2-461c-9c83-336f22afd021)

I left the Processor_Port as 9000d. Where would I find the correct number?

Note: CP3 and Shelly are on different subnets. However, CP3 is on the Main LAN that has access to the Shelly one (IoT).

This is on a CP3. Compiling went fine.

I would greatly appreciate your guidance. Thanks!

**Comment by jbasen** [comment]
Hi,
Couple of things
1) You need to change the device IP.  Instead of entering "http://192.168.20.176" in the parameter field, you need to just enter "192.168.20.176" (without the quotes).  This should fix most of your problems.

2) You  can use almost any port.  9000d is fine as long as it doesn't conflict with something else you are doing on your CP3 with IoT communications.  However, when you setup your webhooks on the Shelly plug as described in the help file you need to make sure you use the same port in your webhook.

3) To be able to retrieve power readings from the plug you need to set the Power_Meter_API path.  Shelly has used different paths on so many of their different devices that I can't keep up with which path works with different devices.  So, once you get the other things working, you can try the different settings for this field and see which one works.

Let me know how this goes.

**Comment by waffles0042** [comment]
Thanks much @jbasen ; I changed the IP on in the Comm Manager and Relay symbol. Now it's working: control and fb.  I may tackle the power readings at a later stage, as I have currently no use for them.  
Thanks again for your help and sharing your outstanding work with the community here in the first place!

**Comment by jbasen** [comment]
Thanks.  I'm glad it was that easy
