### ISSUE TITLE
RGBW Globes

### ISSUE THREAD

**Issue by LukeAus2** [jbasen/Crestron-Shelly#9]
Really impressed with your work here! Shelly should be paying you to make these modules!

Just wondering if you have plans to support the RGBW globes?
Thanks!

**Comment by jbasen** [comment]
Thanks.  I had missed the RGBW bulbs.  I found one sitting in a box so I'll add it to the suite.  Just a warning, it won't happen until the end of May at the earliest as I have a number of other projects to get done between now and then.

**Comment by jbasen** [comment]
I've uploaded a beta version of the Shelly.clz file that I believe fixes a bug that kept the Shelly S+ RGBW module from controlling a Shelly RGBW bulb.  I've only been able to do very limited testing with this which is why I'm calling it beta.  I also haven't been able to test whether the change I made impacted the code's ability to control the Shelly RGBW2.  I'm going to leave this issue open so any bugs can be reported.  However, I've squeezed in making this available before getting tied up on a project so  I won't be able to respond to issues until that work is behind me.  Thanks
